name: easy_search_bar_2
description: AppBar with animated search functionality that can be used as regular or floating AppBar
version: 1.0.0-alpha.0
homepage: https://github.com/ThexXTURBOXx/flutter_easy_search_bar_2
repository: https://github.com/ThexXTURBOXx/flutter_easy_search_bar_2
issue_tracker: https://github.com/ThexXTURBOXx/flutter_easy_search_bar_2/issues
funding:
  - https://github.com/sponsors/ThexXTURBOXx
screenshots:
  - description: 'easy_search_bar_2 in action #1'
    path: preview/preview.gif
  - description: 'easy_search_bar_2 in action #2'
    path: preview/preview2.gif
topics:
  - appbar
  - navigation
  - search
  - ui
  - widgets

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
