name: easy_search_bar
description: AppBar with animated search functionality that can be used as regular or floating AppBar
version: 3.0.0
homepage: https://github.com/4inka/flutter_easy_search_bar

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
